### ISSUE TITLE
UserInfo does not check for declared key usage when selecting encryption key

### ISSUE THREAD

**Issue by matteo-s** [italia/spid-cie-oidc-django#294] opened 2023-12-15 14:07 UTC
While building the userInfo response the provider fetches the client keys and then merely picks the first with a non-empty `kid`, without checking it's intended usage.
If the client exposes 2 keys, one for signing and one for encryption, the provider by picking the first will either:
* pick the right one (by luck) just because it is the first in the list
* pick the wrong one and use the `sig` key against it's intended usage 

https://github.com/italia/spid-cie-oidc-django/blob/2b0c2eff271ef290f90f62ba8b7a3d508b887543/spid_cie_oidc/provider/views/userinfo_endpoint.py#L95
```
        for k in client_jwks:
            if k.get('kid') and len(k["kid"]) >= 1:
                client_jwk = k
                break
```

**Comment by peppelinux** [comment] 2023-12-15 14:50
the lookup happens with the key, since the key usage is not defined in the current specs

the issue is confirmed here https://github.com/italia/spid-cie-oidc-django/blob/2b0c2eff271ef290f90f62ba8b7a3d508b887543/spid_cie_oidc/provider/views/userinfo_endpoint.py#L94C1-L94C1

the approach would be instead using this function by passing the jwt and the attested jwk set
https://github.com/italia/spid-cie-oidc-django/blob/b7b28a8fbb59076dc8d7ba389383379282547315/spid_cie_oidc/entity/utils.py#L57

if you can do that, please open a PR, I'll be happy to review it and merge and having a new release with your formal contribution

**Comment by peppelinux** [comment] 2023-12-15 14:54
Ok, we just have to create a utility function, like this https://github.com/italia/spid-cie-oidc-django/blob/b7b28a8fbb59076dc8d7ba389383379282547315/spid_cie_oidc/entity/utils.py#L57 where an jwks is passed and an argument set(enc, sig) to get the first key according to the scope

in the current specs we don't have defined this detail about the key but it is a good practice having different keys for different scopes

**Comment by rglauco** [comment] 2024-03-13 14:19
Fixed in https://github.com/italia/spid-cie-oidc-django/pull/311

**Closed by rglauco** 2024-03-13 14:19 UTC
Labels: bug, help wanted
