### ISSUE TITLE
Default "cie provider" looks like a spid provider

### ISSUE THREAD

**Issue by matteo-s** [italia/spid-cie-oidc-django#289] opened 2023-12-13 12:29 UTC
The default provider for cie (http://cie-provider.org:8002/oidc/op) acts like a spid provider.
Docs say
```
The demo proposes a small federation composed by the following entities:

*    Federation Authority, acts as trust anchor and onboarding system. It's available at http://127.0.0.1:8000/. It has also an embedded Spid provider and a embedded Relying Party available at /oidc/rp/landing.
*    OpenID Relying Party, available at http://127.0.0.1:8001/
*    CIE OpenID Provider, available at http://127.0.0.1:8002/
```

But the provider at 8002 is by default configured as SPID, and thus accepts only spid scopes etc..
https://github.com/italia/spid-cie-oidc-django/blob/2b0c2eff271ef290f90f62ba8b7a3d508b887543/examples/provider/provider/settingslocal.py.example#L22

**Comment by peppelinux** [comment] 2023-12-13 22:21
good catch @matteo-s 

it seems a misconfiguration caused by some regressions, here @rglauco 
https://github.com/italia/spid-cie-oidc-django/commit/bc18b35353cef314c488d329c3b93023731dcd05#diff-ff79037fba0645fc7f40eee8a417ec53abc7e71d8d5e7bde79b6c15be872757f

I'm happy about you diligently attentions on this, thank you guys

**Comment by rglauco** [comment] 2023-12-14 08:50
fixed in https://github.com/italia/spid-cie-oidc-django/pull/291
my apologies

**Closed** 2023-12-14 22:21 UTC
